[32mINFO    [0m root:test_15_servermonitor.py:28 ==========开始执行用例：servermonitor_serverlist_01==========
[32mINFO    [0m root:runcase.py:31 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 START-·-·-·-·-·-·-·-·-·-
[32mINFO    [0m root:handleyaml.py:94 Yaml测试用例基础架构检查通过
[32mINFO    [0m root:runcase.py:50 重组后的用例信息：{'name': '查询服务器列表', 'description': '查询服务器列表', 'validate': {'code': 200, 'response': {'statusCode': 0, 'msg': 'success'}}, 'epic': '系统管理', 'feature': '运维管理-服务监控', 'story': '查询服务器列表接口', 'base_url': 'https://192.168.148.174:31000', 'request': {'method': 'GET', 'address': '/api/auth/v1/monitor/servers', 'headers': {'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6Ijc2ZDQ0NmFlLTdkMGEtNDVhYy04NzE0LTgxNmQzMzRjYzg4ZSIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI3NmQ0NDZhZS03ZDBhLTQ1YWMtODcxNC04MTZkMzM0Y2M4OGUiLCJleHAiOjE2ODgxMjIyMDEsImlhdCI6MTY4Nzk0MjIwMX0.FWYPT5nPgOdBtOT0wGRVZNVTB6oggV1ehXLgP2gppALL2Djxp_46T_KhaOizqJlxUPAYRWJs7nKHiU-ug2qGKA', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/sysManage/systemOperation/operationMonitoring/index'}}, 'caseid': 'servermonitor_serverlist_01'}
[32mINFO    [0m root:runcase.py:81 请求地址：https://192.168.148.174:31000/api/auth/v1/monitor/servers
[32mINFO    [0m root:runcase.py:82 请求方法：GET
[32mINFO    [0m root:runcase.py:83 请求头：{'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6Ijc2ZDQ0NmFlLTdkMGEtNDVhYy04NzE0LTgxNmQzMzRjYzg4ZSIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI3NmQ0NDZhZS03ZDBhLTQ1YWMtODcxNC04MTZkMzM0Y2M4OGUiLCJleHAiOjE2ODgxMjIyMDEsImlhdCI6MTY4Nzk0MjIwMX0.FWYPT5nPgOdBtOT0wGRVZNVTB6oggV1ehXLgP2gppALL2Djxp_46T_KhaOizqJlxUPAYRWJs7nKHiU-ug2qGKA', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/sysManage/systemOperation/operationMonitoring/index'}
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): 192.168.148.174:31000
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://192.168.148.174:31000 "GET /api/auth/v1/monitor/servers HTTP/1.1" 200 266
[32mINFO    [0m root:runcase.py:166 请求接口结果： {'statusCode': 0, 'msg': 'success', 'data': {'totalCount': 24256, 'list': [{'id': 55533, 'modifyTime': '2023-06-28T08:54:15.000+00:00', 'endpointId': 1, 'serverIp': '192.168.148.174', 'cpuUsed': '31.10735418252374', 'memoryUsed': '49.23964913531406', 'diskUsed': '3.8502839521250607'}]}}
[32mINFO    [0m root:checkresult.py:152 code断言通过, 期望状态码:200, 实际状态码:200
[32mINFO    [0m root:checkresult.py:87 返回结果断言通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 0, 'msg': 'success', 'data': {'totalCount': 24256, 'list': [{'id': 55533, 'modifyTime': '2023-06-28T08:54:15.000+00:00', 'endpointId': 1, 'serverIp': '192.168.148.174', 'cpuUsed': '31.10735418252374', 'memoryUsed': '49.23964913531406', 'diskUsed': '3.8502839521250607'}]}}
[32mINFO    [0m root:runcase.py:61 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 END-·-·-·-·-·-·-·-·-·-