INFO     root:test_17_logbackup.py:82 ==========开始执行用例：logbackup_deleteconfig_01==========
INFO     root:runcase.py:30 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 START-·-·-·-·-·-·-·-·-·-
INFO     root:handleyaml.py:94 Yaml测试用例基础架构检查通过
INFO     root:runcase.py:30 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 START-·-·-·-·-·-·-·-·-·-
INFO     root:handleyaml.py:94 Yaml测试用例基础架构检查通过
INFO     root:runcase.py:47 重组后的用例信息：{'name': '按name_database查询备份', 'description': '按name_database查询备份', 'request': {'data': {'nameDatabase': 'sas_v3_doc'}, 'method': 'POST', 'address': '/api/auth/v1/log/queryBackupConfigByNameDatabase', 'headers': {'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6ImY2MzRmNDkyLTM0NjktNGU2Yi05NTI4LTQwNGQxOTdjZjBkNyIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiJmNjM0ZjQ5Mi0zNDY5LTRlNmItOTUyOC00MDRkMTk3Y2YwZDciLCJleHAiOjE2ODc5NDAzNDIsImlhdCI6MTY4Nzc2MDM0Mn0.AlXTVLxZrmNgDRvtdV-Lwy0OeP8VGt-QOwjVWR7TCo1cHLTNKZ39YvetKwmd8KQDqe-AscMfoPux5PiXN1rafQ', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/syslogBackUp'}}, 'validate': {'code': 200, 'response': {'statusCode': 0, 'msg': 'success'}}, 'epic': '系统管理', 'feature': '运维管理-日志备份配置', 'story': '按name_database查询备份配置接口', 'base_url': 'https://192.168.148.174:31000', 'caseid': 'logbackup_listconfig_bydb_01'}
INFO     root:runcase.py:83 请求地址：https://192.168.148.174:31000/api/auth/v1/log/queryBackupConfigByNameDatabase
INFO     root:runcase.py:84 请求方法：POST
INFO     root:runcase.py:85 请求头：{'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6ImY2MzRmNDkyLTM0NjktNGU2Yi05NTI4LTQwNGQxOTdjZjBkNyIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiJmNjM0ZjQ5Mi0zNDY5LTRlNmItOTUyOC00MDRkMTk3Y2YwZDciLCJleHAiOjE2ODc5NDAzNDIsImlhdCI6MTY4Nzc2MDM0Mn0.AlXTVLxZrmNgDRvtdV-Lwy0OeP8VGt-QOwjVWR7TCo1cHLTNKZ39YvetKwmd8KQDqe-AscMfoPux5PiXN1rafQ', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/syslogBackUp'}
INFO     root:runcase.py:95 请求参数：{'nameDatabase': 'sas_v3_doc'}
DEBUG    urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): 192.168.148.174:31000
DEBUG    urllib3.connectionpool:connectionpool.py:456 https://192.168.148.174:31000 "POST /api/auth/v1/log/queryBackupConfigByNameDatabase HTTP/1.1" 200 600
INFO     root:runcase.py:157 请求接口结果： {'statusCode': 0, 'msg': 'success', 'data': {'id': 12, 'description': '终端日志备份-自动化测试修改', 'isRemoved': 0, 'savePath': '/BackupData', 'realPath': '/home/docker/volumes/esBackupData/_data', 'nameDatabase': 'sas_v3_doc', 'backupTime': None, 'backupTaskName': '终端日志备份修改', 'firstExecutionTime': '2023-06-26 15:25:35', 'dataQuantity': None, 'retentionTime': '1', 'retentionUnit': '2', 'intervalPeriod': '2', 'cycleUnit': '2', 'cCreateTime': '2023-06-26 14:22:57', 'cCreater': 'B5A33586-15104954-9B752AE1-53333EC10', 'cUpdateTime': '2023-06-26 14:22:57', 'cUpdater': 'B5A33586-15104954-9B752AE1-53333EC10'}}
INFO     root:checkresult.py:113 code断言通过, 期望状态码:200, 实际状态码:200
INFO     root:checkresult.py:48 返回结果断言通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 0, 'msg': 'success', 'data': {'id': 12, 'description': '终端日志备份-自动化测试修改', 'isRemoved': 0, 'savePath': '/BackupData', 'realPath': '/home/docker/volumes/esBackupData/_data', 'nameDatabase': 'sas_v3_doc', 'backupTime': None, 'backupTaskName': '终端日志备份修改', 'firstExecutionTime': '2023-06-26 15:25:35', 'dataQuantity': None, 'retentionTime': '1', 'retentionUnit': '2', 'intervalPeriod': '2', 'cycleUnit': '2', 'cCreateTime': '2023-06-26 14:22:57', 'cCreater': 'B5A33586-15104954-9B752AE1-53333EC10', 'cUpdateTime': '2023-06-26 14:22:57', 'cUpdater': 'B5A33586-15104954-9B752AE1-53333EC10'}}
INFO     root:runcase.py:63 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 END-·-·-·-·-·-·-·-·-·-
INFO     root:runcase.py:47 重组后的用例信息：{'name': '删除备份配置', 'description': '删除备份配置', 'request': {'data': {'id': '12'}, 'method': 'POST', 'address': '/api/auth/v1/log/delBackupConfig', 'headers': {'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6ImY2MzRmNDkyLTM0NjktNGU2Yi05NTI4LTQwNGQxOTdjZjBkNyIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiJmNjM0ZjQ5Mi0zNDY5LTRlNmItOTUyOC00MDRkMTk3Y2YwZDciLCJleHAiOjE2ODc5NDAzNDIsImlhdCI6MTY4Nzc2MDM0Mn0.AlXTVLxZrmNgDRvtdV-Lwy0OeP8VGt-QOwjVWR7TCo1cHLTNKZ39YvetKwmd8KQDqe-AscMfoPux5PiXN1rafQ', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/syslogBackUp'}}, 'relevance': [{'caseid': 'logbackup_listconfig_bydb_01', 'response': [{'value': '$.data.id', 'name': 'id'}]}], 'validate': {'code': 200, 'response': {'statusCode': 0, 'msg': 'success'}}, 'epic': '系统管理', 'feature': '运维管理-日志备份配置', 'story': '删除备份配置接口', 'base_url': 'https://192.168.148.174:31000', 'caseid': 'logbackup_deleteconfig_01'}
INFO     root:runcase.py:83 请求地址：https://192.168.148.174:31000/api/auth/v1/log/delBackupConfig
INFO     root:runcase.py:84 请求方法：POST
INFO     root:runcase.py:85 请求头：{'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6ImY2MzRmNDkyLTM0NjktNGU2Yi05NTI4LTQwNGQxOTdjZjBkNyIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiJmNjM0ZjQ5Mi0zNDY5LTRlNmItOTUyOC00MDRkMTk3Y2YwZDciLCJleHAiOjE2ODc5NDAzNDIsImlhdCI6MTY4Nzc2MDM0Mn0.AlXTVLxZrmNgDRvtdV-Lwy0OeP8VGt-QOwjVWR7TCo1cHLTNKZ39YvetKwmd8KQDqe-AscMfoPux5PiXN1rafQ', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/syslogBackUp'}
INFO     root:runcase.py:95 请求参数：{'id': '12'}
DEBUG    urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): 192.168.148.174:31000
DEBUG    urllib3.connectionpool:connectionpool.py:456 https://192.168.148.174:31000 "POST /api/auth/v1/log/delBackupConfig HTTP/1.1" 200 32
INFO     root:runcase.py:157 请求接口结果： {'statusCode': 0, 'msg': 'success'}
INFO     root:checkresult.py:113 code断言通过, 期望状态码:200, 实际状态码:200
INFO     root:checkresult.py:48 返回结果断言通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 0, 'msg': 'success'}
INFO     root:runcase.py:63 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 END-·-·-·-·-·-·-·-·-·-