INFO     root:test_02_usersync.py:110 ==========开始执行用例：usersync_syncConfig_sync_01==========
INFO     root:runcase.py:29 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 START-·-·-·-·-·-·-·-·-·-
INFO     root:handleyaml.py:94 Yaml测试用例基础架构检查通过
INFO     root:runcase.py:29 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 START-·-·-·-·-·-·-·-·-·-
INFO     root:handleyaml.py:94 Yaml测试用例基础架构检查通过
INFO     root:runcase.py:45 重组后的用例信息：{'name': '查询所有同步配置', 'description': '查询所有同步配置', 'validate': {'code': 200, 'response': {'statusCode': 0, 'msg': 'success'}}, 'epic': '用户管理', 'feature': '用户同步管理-用户同步', 'story': '查询所有同步配置接口', 'base_url': 'https://192.168.148.174:31000', 'request': {'method': 'GET', 'address': '/api/usersync/v1/syncConfig', 'headers': {'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6IjI3MTM3NmQzLTBiZDktNDQ0Ni05ZGU5LThlMDZmM2YwM2Q4ZCIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiIyNzEzNzZkMy0wYmQ5LTQ0NDYtOWRlOS04ZTA2ZjNmMDNkOGQiLCJleHAiOjE2ODcxOTM3MzMsImlhdCI6MTY4NzAxMzczM30.Biu_6v1RwD72vA1X9gTejk7wW0bRoGbthwJGX28Y0XqDcwnzZ5VxENlK6o8nogaP5oEhcuhUrITOGgpvz2gh6w', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userSync'}}, 'caseid': 'usersync_syncConfig_alllist_01'}
INFO     root:runcase.py:81 请求地址：https://192.168.148.174:31000/api/usersync/v1/syncConfig
INFO     root:runcase.py:82 请求方法：GET
INFO     root:runcase.py:83 请求头：{'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6IjI3MTM3NmQzLTBiZDktNDQ0Ni05ZGU5LThlMDZmM2YwM2Q4ZCIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiIyNzEzNzZkMy0wYmQ5LTQ0NDYtOWRlOS04ZTA2ZjNmMDNkOGQiLCJleHAiOjE2ODcxOTM3MzMsImlhdCI6MTY4NzAxMzczM30.Biu_6v1RwD72vA1X9gTejk7wW0bRoGbthwJGX28Y0XqDcwnzZ5VxENlK6o8nogaP5oEhcuhUrITOGgpvz2gh6w', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userSync'}
DEBUG    urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): 192.168.148.174:31000
DEBUG    urllib3.connectionpool:connectionpool.py:456 https://192.168.148.174:31000 "GET /api/usersync/v1/syncConfig HTTP/1.1" 200 266
INFO     root:runcase.py:158 请求接口结果： {'statusCode': 0, 'msg': 'success', 'data': [{'id': 8, 'modifyTime': '2023-06-17 22:58:35', 'userSourceId': '19', 'jobTime': '00 39 15 10 * ?', 'isIncrement': 1, 'threshold': 0, 'taskSavePeriod': 180, 'syncName': '自动化测试同步配置修改', 'syncType': '0', 'allowUpdate': False}]}
INFO     root:checkresult.py:111 code断言通过, 期望状态码:200, 实际状态码:200
INFO     root:checkresult.py:46 返回结果断言通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 0, 'msg': 'success', 'data': [{'id': 8, 'modifyTime': '2023-06-17 22:58:35', 'userSourceId': '19', 'jobTime': '00 39 15 10 * ?', 'isIncrement': 1, 'threshold': 0, 'taskSavePeriod': 180, 'syncName': '自动化测试同步配置修改', 'syncType': '0', 'allowUpdate': False}]}
INFO     root:runcase.py:61 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 END-·-·-·-·-·-·-·-·-·-
INFO     root:runcase.py:45 重组后的用例信息：{'name': 'LADP域立即同步', 'description': '同步LADP数据源', 'request': {'data': {'syncConfigId': '8'}, 'method': 'PUT', 'address': '/api/usersync/v1/sync', 'headers': {'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6IjI3MTM3NmQzLTBiZDktNDQ0Ni05ZGU5LThlMDZmM2YwM2Q4ZCIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiIyNzEzNzZkMy0wYmQ5LTQ0NDYtOWRlOS04ZTA2ZjNmMDNkOGQiLCJleHAiOjE2ODcxOTM3MzMsImlhdCI6MTY4NzAxMzczM30.Biu_6v1RwD72vA1X9gTejk7wW0bRoGbthwJGX28Y0XqDcwnzZ5VxENlK6o8nogaP5oEhcuhUrITOGgpvz2gh6w', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userSync'}}, 'relevance': [{'caseid': 'usersync_syncConfig_alllist_01', 'response': [{'value': '$.data[0].id', 'name': 'syncConfigId'}]}], 'validate': {'code': 200, 'response': {'statusCode': 0, 'msg': 'success'}}, 'epic': '用户管理', 'feature': '用户同步管理-用户同步', 'story': '立即同步接口', 'base_url': 'https://192.168.148.174:31000', 'caseid': 'usersync_syncConfig_sync_01'}
INFO     root:runcase.py:81 请求地址：https://192.168.148.174:31000/api/usersync/v1/sync
INFO     root:runcase.py:82 请求方法：PUT
INFO     root:runcase.py:83 请求头：{'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6IjI3MTM3NmQzLTBiZDktNDQ0Ni05ZGU5LThlMDZmM2YwM2Q4ZCIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiIyNzEzNzZkMy0wYmQ5LTQ0NDYtOWRlOS04ZTA2ZjNmMDNkOGQiLCJleHAiOjE2ODcxOTM3MzMsImlhdCI6MTY4NzAxMzczM30.Biu_6v1RwD72vA1X9gTejk7wW0bRoGbthwJGX28Y0XqDcwnzZ5VxENlK6o8nogaP5oEhcuhUrITOGgpvz2gh6w', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userSync'}
INFO     root:runcase.py:93 请求参数：{'syncConfigId': '8'}
DEBUG    urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): 192.168.148.174:31000
DEBUG    urllib3.connectionpool:connectionpool.py:456 https://192.168.148.174:31000 "PUT /api/usersync/v1/sync HTTP/1.1" 200 32
INFO     root:runcase.py:175 请求接口结果： {'statusCode': 0, 'msg': 'success'}
INFO     root:checkresult.py:111 code断言通过, 期望状态码:200, 实际状态码:200
INFO     root:checkresult.py:46 返回结果断言通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 0, 'msg': 'success'}
INFO     root:runcase.py:61 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 END-·-·-·-·-·-·-·-·-·-