INFO     root:test_17_logbackup.py:55 ==========开始执行用例：logbackup_list_dbbackup_02==========
INFO     root:runcase.py:31 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 START-·-·-·-·-·-·-·-·-·-
INFO     root:handleyaml.py:94 Yaml测试用例基础架构检查通过
INFO     root:runcase.py:50 重组后的用例信息：{'name': '查询数据库所有备份信息-按时间筛选', 'description': '查询数据库所有备份信息-按时间筛选', 'request': {'data': {'nameDatabase': 'sas_v3_doc', 'start': '2023-06-27 00:00:00', 'end': '2023-06-28 00:00:00', 'pageNum': 1, 'pageSize': 20}, 'method': 'POST', 'address': '/api/auth/v1/log/queryBackupInfoByNameDatabase', 'headers': {'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6Ijc0Njc3NmJiLWZjZmMtNGMyOC1hMzY3LTY0ODBlNGE5ZmEwMyIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI3NDY3NzZiYi1mY2ZjLTRjMjgtYTM2Ny02NDgwZTRhOWZhMDMiLCJleHAiOjE2ODgwNDI1OTQsImlhdCI6MTY4Nzg2MjU5NH0.O8P51iQijd4dXdw9AlM9NRCQ6SLu28ZirspvKrfBk3eeSCluJZHOpr6MJ7D9V_kPAK1ed1IpQkvahME21OjbVg', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/syslogBackUp'}}, 'validate': {'code': 200, 'response': {'statusCode': 0, 'msg': 'success'}}, 'epic': '系统管理', 'feature': '运维管理-日志备份配置', 'story': '查询数据库所有备份信息接口', 'base_url': 'https://192.168.148.174:31000', 'caseid': 'logbackup_list_dbbackup_02'}
INFO     root:runcase.py:81 请求地址：https://192.168.148.174:31000/api/auth/v1/log/queryBackupInfoByNameDatabase
INFO     root:runcase.py:82 请求方法：POST
INFO     root:runcase.py:83 请求头：{'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6Ijc0Njc3NmJiLWZjZmMtNGMyOC1hMzY3LTY0ODBlNGE5ZmEwMyIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI3NDY3NzZiYi1mY2ZjLTRjMjgtYTM2Ny02NDgwZTRhOWZhMDMiLCJleHAiOjE2ODgwNDI1OTQsImlhdCI6MTY4Nzg2MjU5NH0.O8P51iQijd4dXdw9AlM9NRCQ6SLu28ZirspvKrfBk3eeSCluJZHOpr6MJ7D9V_kPAK1ed1IpQkvahME21OjbVg', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/syslogBackUp'}
INFO     root:runcase.py:93 请求参数：{'nameDatabase': 'sas_v3_doc', 'start': '2023-06-27 00:00:00', 'end': '2023-06-28 00:00:00', 'pageNum': 1, 'pageSize': 20}
DEBUG    urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): 192.168.148.174:31000
DEBUG    urllib3.connectionpool:connectionpool.py:456 https://192.168.148.174:31000 "POST /api/auth/v1/log/queryBackupInfoByNameDatabase HTTP/1.1" 200 66
INFO     root:runcase.py:155 请求接口结果： {'statusCode': 0, 'msg': 'success', 'data': {'totalCount': 0, 'list': []}}
INFO     root:checkresult.py:113 code断言通过, 期望状态码:200, 实际状态码:200
INFO     root:checkresult.py:48 返回结果断言通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 0, 'msg': 'success', 'data': {'totalCount': 0, 'list': []}}
INFO     root:runcase.py:61 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 END-·-·-·-·-·-·-·-·-·-