{"name": "获取同步根组id", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <bms.testcases.test_02_usersync.TestUserSync object at 0x00000233A91A1A30>\ncaseid = 'usersync_get_syncgroupid_01'\ncasedata = {'base_url': '${config(host)}', 'caseid': 'usersync_get_syncgroupid_01', 'description': '获取同步根组id', 'epic': '用户管理', ...}\n\n    @pytest.mark.parametrize('caseid, casedata', [(caseid, casedata) for caseid, casedata in\n                                                  readcase.ReadCase().get_case_dict(\n                                                      ROOT_DIR + 'bms/data/usersync/usersync_get_syncgroupid.yaml').items()])\n    def test_usersync_get_syncgroupid(self, caseid, casedata):\n        handleallure.allure_display(casedata)\n        logging.info(\"==========开始执行用例：%s==========\", caseid)\n>       runcase.excute_case(casedata)\n\nbms\\testcases\\test_02_usersync.py:165: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncommon\\runcase.py:55: in excute_case\n    checkresult.check_result(hope_result, recv_data, recv_code)\ncommon\\checkresult.py:31: in check_result\n    assert_response(value, real_res)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nhope_res = {'msg': 'success', 'statusCode': 0}, real_res = {'msg': '找不到对应的组织机构', 'statusCode': 1114886}\n\n    def assert_response(hope_res, real_res):\n        \"\"\"\n        返回结果校验 -全返回校验\n        :param hope_res:\n        :param real_res:\n        :return:\n        \"\"\"\n        try:\n            with allure.step(\"返回值校验\"):\n                allure.attach(name=\"期望返回值\", body=str(hope_res))\n                allure.attach(name='实际返回值', body=str(real_res))\n                if isinstance(hope_res, (dict, list)) and isinstance(real_res, (dict, list)):\n                    flag = handledict.cmp_dict(hope_res, real_res)\n>                   assert flag\nE                   AssertionError\n\ncommon\\checkresult.py:84: AssertionError"}, "description": "获取同步根组id", "steps": [{"name": "执行关联接口", "status": "passed", "steps": [{"name": "执行当前接口：同步任务列表搜索-无搜索条件", "status": "passed", "attachments": [{"name": "请求方法：", "source": "13a027ef-f12c-4941-88b3-7c308e68fa16-attachment.attach"}, {"name": "请求地址", "source": "ce38886d-4f1d-4867-a09c-fb634290cb44-attachment.attach"}, {"name": "请求头", "source": "5020577d-eb34-48cd-b735-2bbc8105dd3a-attachment.attach"}, {"name": "请求参数", "source": "1bfbb4f6-b85e-4800-90ae-97b3b444ad46-attachment.attach"}, {"name": "请求结果", "source": "f926b426-012a-40f1-962f-70acd409b39c-attachment.attach"}], "start": 1687942564194, "stop": 1687942564271}, {"name": "结果校验", "status": "passed", "steps": [{"name": "状态码校验", "status": "passed", "attachments": [{"name": "期望状态码", "source": "06273af7-ff79-4db6-b470-2a509dca25c6-attachment.attach"}, {"name": "实际状态码", "source": "9bf1b8ce-1664-4033-a45e-b4002d8e6f92-attachment.attach"}], "start": 1687942564271, "stop": 1687942564274}, {"name": "返回值校验", "status": "passed", "attachments": [{"name": "期望返回值", "source": "8d5e172d-df52-4cc0-a2d3-08fc8be01108-attachment.attach"}, {"name": "实际返回值", "source": "75dfa32e-1788-407f-81a8-756312531b58-attachment.attach"}], "start": 1687942564274, "stop": 1687942564551}], "start": 1687942564271, "stop": 1687942564552}], "start": 1687942564177, "stop": 1687942564553}, {"name": "执行当前接口：获取同步根组id", "status": "passed", "attachments": [{"name": "请求方法：", "source": "ffb058a2-51d8-4d23-9c47-f8493f703580-attachment.attach"}, {"name": "请求地址", "source": "5476aa0a-7eff-4681-bb64-54f2eea3dd7e-attachment.attach"}, {"name": "请求头", "source": "104828e0-3931-4fb8-a272-f57dd8e38f26-attachment.attach"}, {"name": "请求参数", "source": "4b4e1d51-2b99-4ab5-a9cf-d5358f1b0ae0-attachment.attach"}, {"name": "请求结果", "source": "9afc711f-15e2-448e-9fc2-58ba068b0d97-attachment.attach"}], "start": 1687942564554, "stop": 1687942564640}, {"name": "结果校验", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 31, in check_result\n    assert_response(value, real_res)\n  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 84, in assert_response\n    assert flag\n"}, "steps": [{"name": "状态码校验", "status": "passed", "attachments": [{"name": "期望状态码", "source": "197bb828-b6ef-4770-866a-650fa0ac759b-attachment.attach"}, {"name": "实际状态码", "source": "80bc3a3e-b80c-4b52-9c4b-4bfccced2e61-attachment.attach"}], "start": 1687942564640, "stop": 1687942564641}, {"name": "返回值校验", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 84, in assert_response\n    assert flag\n"}, "attachments": [{"name": "期望返回值", "source": "4017f20f-9d26-4d5b-a4d0-be5bf35dfed2-attachment.attach"}, {"name": "实际返回值", "source": "5e86b77c-bd51-4fa0-aef1-e08e50b7c7c8-attachment.attach"}], "start": 1687942564641, "stop": 1687942564642}], "start": 1687942564640, "stop": 1687942564643}], "attachments": [{"name": "log", "source": "8d24bd03-d9ef-47f3-8b91-1e2ee6830055-attachment.txt", "type": "text/plain"}], "start": 1687942564171, "stop": 1687942564643, "uuid": "198caaf2-6447-4cc0-9890-eadc9d5b4306", "historyId": "c076d0bb657b7fadcb6dc7f1415a3243", "testCaseId": "8a41af8eca098c4295d5e872d129839c", "fullName": "bms.testcases.test_02_usersync.TestUserSync#test_usersync_get_syncgroupid", "labels": [{"name": "epic", "value": "用户管理"}, {"name": "feature", "value": "用户同步管理-用户同步"}, {"name": "story", "value": "编辑，获取同步根组id接口"}, {"name": "parentSuite", "value": "bms.testcases"}, {"name": "suite", "value": "test_02_usersync"}, {"name": "subSuite", "value": "TestUserSync"}, {"name": "host", "value": "OFYI7JX9DURTDV6"}, {"name": "thread", "value": "14556-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "bms.testcases.test_02_usersync"}]}