INFO     root:test_17_logbackup.py:28 ==========开始执行用例：logbackup_databaselist_01==========
INFO     root:runcase.py:30 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 START-·-·-·-·-·-·-·-·-·-
INFO     root:handleyaml.py:94 Yaml测试用例基础架构检查通过
INFO     root:runcase.py:47 重组后的用例信息：{'name': '查询数据库列表', 'description': '查询数据库列表', 'validate': {'code': 200, 'response': {'statusCode': 0, 'msg': 'success'}}, 'epic': '系统管理', 'feature': '运维管理-日志备份配置', 'story': '查询数据库接口', 'base_url': 'https://192.168.148.174:31000', 'request': {'method': 'POST', 'address': '/api/auth/v1/log/queryDatabases', 'headers': {'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6IjY1OTBhNTE1LTA0Y2EtNDA5ZS1hNzBmLWMxZDk2MDY1MTU5MiIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI2NTkwYTUxNS0wNGNhLTQwOWUtYTcwZi1jMWQ5NjA2NTE1OTIiLCJleHAiOjE2ODgwMzE2MjMsImlhdCI6MTY4Nzg1MTYyM30.ZQ97PBbwO0FxfTBcZAH7cNMO0z8M0fncEgMdMVNutTK5fS6qwMFhZur757v9anwBP_z2errE-UoAcB88J2n1ag', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/syslogBackUp'}}, 'caseid': 'logbackup_databaselist_01'}
INFO     root:runcase.py:83 请求地址：https://192.168.148.174:31000/api/auth/v1/log/queryDatabases
INFO     root:runcase.py:84 请求方法：POST
INFO     root:runcase.py:85 请求头：{'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6IjY1OTBhNTE1LTA0Y2EtNDA5ZS1hNzBmLWMxZDk2MDY1MTU5MiIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiI2NTkwYTUxNS0wNGNhLTQwOWUtYTcwZi1jMWQ5NjA2NTE1OTIiLCJleHAiOjE2ODgwMzE2MjMsImlhdCI6MTY4Nzg1MTYyM30.ZQ97PBbwO0FxfTBcZAH7cNMO0z8M0fncEgMdMVNutTK5fS6qwMFhZur757v9anwBP_z2errE-UoAcB88J2n1ag', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/syslogBackUp'}
DEBUG    urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): 192.168.148.174:31000
DEBUG    urllib3.connectionpool:connectionpool.py:456 https://192.168.148.174:31000 "POST /api/auth/v1/log/queryDatabases HTTP/1.1" 200 69
INFO     root:runcase.py:157 请求接口结果： {'statusCode': 0, 'msg': 'success', 'data': ['sas_ndlp_doc', 'sas_v3_doc']}
INFO     root:checkresult.py:113 code断言通过, 期望状态码:200, 实际状态码:200
INFO     root:checkresult.py:48 返回结果断言通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 0, 'msg': 'success', 'data': ['sas_ndlp_doc', 'sas_v3_doc']}
INFO     root:runcase.py:63 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 END-·-·-·-·-·-·-·-·-·-