{"name": "获取同步根组id", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <bms.testcases.test_02_usersync.TestUserSync object at 0x00000233A91A1A30>\ncaseid = 'usersync_get_syncgroupid_01'\ncasedata = {'base_url': '${config(host)}', 'caseid': 'usersync_get_syncgroupid_01', 'description': '获取同步根组id', 'epic': '用户管理', ...}\n\n    @pytest.mark.parametrize('caseid, casedata', [(caseid, casedata) for caseid, casedata in\n                                                  readcase.ReadCase().get_case_dict(\n                                                      ROOT_DIR + 'bms/data/usersync/usersync_get_syncgroupid.yaml').items()])\n    def test_usersync_get_syncgroupid(self, caseid, casedata):\n        handleallure.allure_display(casedata)\n        logging.info(\"==========开始执行用例：%s==========\", caseid)\n>       runcase.excute_case(casedata)\n\nbms\\testcases\\test_02_usersync.py:165: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncommon\\runcase.py:55: in excute_case\n    checkresult.check_result(hope_result, recv_data, recv_code)\ncommon\\checkresult.py:31: in check_result\n    assert_response(value, real_res)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nhope_res = {'msg': 'success', 'statusCode': 0}, real_res = {'msg': '找不到对应的组织机构', 'statusCode': 1114886}\n\n    def assert_response(hope_res, real_res):\n        \"\"\"\n        返回结果校验 -全返回校验\n        :param hope_res:\n        :param real_res:\n        :return:\n        \"\"\"\n        try:\n            with allure.step(\"返回值校验\"):\n                allure.attach(name=\"期望返回值\", body=str(hope_res))\n                allure.attach(name='实际返回值', body=str(real_res))\n                if isinstance(hope_res, (dict, list)) and isinstance(real_res, (dict, list)):\n                    flag = handledict.cmp_dict(hope_res, real_res)\n>                   assert flag\nE                   AssertionError\n\ncommon\\checkresult.py:84: AssertionError"}, "description": "获取同步根组id", "steps": [{"name": "执行关联接口", "status": "passed", "steps": [{"name": "执行当前接口：同步任务列表搜索-无搜索条件", "status": "passed", "attachments": [{"name": "请求方法：", "source": "5212f122-1634-4930-b6f1-5a440bf626aa-attachment.attach"}, {"name": "请求地址", "source": "587726bd-f5c1-4df8-989a-fdcb329265f4-attachment.attach"}, {"name": "请求头", "source": "af3c114d-fccb-4ecc-b914-2197246b4381-attachment.attach"}, {"name": "请求参数", "source": "519efd64-e4a1-4324-b920-e9f999cb46d1-attachment.attach"}, {"name": "请求结果", "source": "3b9408b8-af76-4bf5-bcb6-175e3c1bcd43-attachment.attach"}], "start": 1687942546724, "stop": 1687942546785}, {"name": "结果校验", "status": "passed", "steps": [{"name": "状态码校验", "status": "passed", "attachments": [{"name": "期望状态码", "source": "f3e99943-4eb2-4012-b245-d8b3882c74b5-attachment.attach"}, {"name": "实际状态码", "source": "a4340f57-b38c-4b23-a5e0-f3f2e4a9e646-attachment.attach"}], "start": 1687942546785, "stop": 1687942546787}, {"name": "返回值校验", "status": "passed", "attachments": [{"name": "期望返回值", "source": "25450a7b-dbe7-4e6c-986d-189f144ae503-attachment.attach"}, {"name": "实际返回值", "source": "feca4bc3-350e-46ca-ad54-614bb724a515-attachment.attach"}], "start": 1687942546787, "stop": 1687942546790}], "start": 1687942546785, "stop": 1687942546790}], "start": 1687942546709, "stop": 1687942546790}, {"name": "执行当前接口：获取同步根组id", "status": "passed", "attachments": [{"name": "请求方法：", "source": "f64ae75e-bb61-4f4f-9789-d69fc74a3dd9-attachment.attach"}, {"name": "请求地址", "source": "6e7a1e09-fe70-401a-af50-189c5f7d6621-attachment.attach"}, {"name": "请求头", "source": "03b49890-a62b-497e-a41e-d306746ecd40-attachment.attach"}, {"name": "请求参数", "source": "166e76a3-0cb5-4355-a202-a03f0992834a-attachment.attach"}, {"name": "请求结果", "source": "57390ae6-589d-487a-b9c7-bcc6723b72e0-attachment.attach"}], "start": 1687942546791, "stop": 1687942546858}, {"name": "结果校验", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 31, in check_result\n    assert_response(value, real_res)\n  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 84, in assert_response\n    assert flag\n"}, "steps": [{"name": "状态码校验", "status": "passed", "attachments": [{"name": "期望状态码", "source": "3e5987df-3f91-4e0d-a782-7e82d4121ecb-attachment.attach"}, {"name": "实际状态码", "source": "240929e0-6e9c-4eff-bcec-65364c94f7b6-attachment.attach"}], "start": 1687942546858, "stop": 1687942546859}, {"name": "返回值校验", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 84, in assert_response\n    assert flag\n"}, "attachments": [{"name": "期望返回值", "source": "035c996c-8cb5-49c9-b17b-19017e1fe50a-attachment.attach"}, {"name": "实际返回值", "source": "3d3aaa24-dfa7-41b3-a21e-255c2bd698b6-attachment.attach"}], "start": 1687942546859, "stop": 1687942546860}], "start": 1687942546858, "stop": 1687942546906}], "attachments": [{"name": "log", "source": "97131987-bce1-4550-892e-3cdf434e8044-attachment.txt", "type": "text/plain"}], "start": 1687942546703, "stop": 1687942546907, "uuid": "50e276c5-af8e-4c95-b4c2-c171ba321535", "historyId": "c076d0bb657b7fadcb6dc7f1415a3243", "testCaseId": "8a41af8eca098c4295d5e872d129839c", "fullName": "bms.testcases.test_02_usersync.TestUserSync#test_usersync_get_syncgroupid", "labels": [{"name": "epic", "value": "用户管理"}, {"name": "feature", "value": "用户同步管理-用户同步"}, {"name": "story", "value": "编辑，获取同步根组id接口"}, {"name": "parentSuite", "value": "bms.testcases"}, {"name": "suite", "value": "test_02_usersync"}, {"name": "subSuite", "value": "TestUserSync"}, {"name": "host", "value": "OFYI7JX9DURTDV6"}, {"name": "thread", "value": "14556-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "bms.testcases.test_02_usersync"}]}