{"name": "测试数据源配置", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <test_cases.TestUserSync object at 0x0000014AE64CC6A0>\ncase = 'config_test'\ncasedata = {'description': '测试数据源配置', 'epic': '用户管理', 'feature': '用户同步管理', 'name': '测试数据源配置', ...}\n\n    @pytest.mark.parametrize('case, casedata', readcase.ReadCase().get_case(businesscase_pathlist))\n    def test_businesscases(self, case, casedata):\n        handleallure.allure_display(casedata)\n        logging.info(\"==========执行用例START：%s==========\", case)\n>       runcase.RunCase().excute_case(casedata)\n\ntestcases\\test_cases.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncommon\\runcase.py:59: in excute_case\n    self.excute_apicase(api, api_casedata)\ncommon\\runcase.py:133: in excute_apicase\n    self.apicase_processors(api_casedata['postProcessors'], recv_data, recv_code)\ncommon\\runcase.py:154: in apicase_processors\n    checkresult.check_result(pro_data['assert'], recv_data, recv_code)\ncommon\\checkresult.py:31: in check_result\n    assert_response(value, real_res)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nhope_res = {'msg': 'success', 'statusCode': 0}\nreal_res = {'msg': '没有连接权限,账号或密码不正确！', 'statusCode': 1114402}\n\n    def assert_response(hope_res, real_res):\n        \"\"\"\n        返回结果校验 -全返回校验\n        :param hope_res:\n        :param real_res:\n        :return:\n        \"\"\"\n        try:\n            with allure.step(\"返回值校验\"):\n                allure.attach(name=\"期望返回值\", body=str(hope_res))\n                allure.attach(name='实际返回值', body=str(real_res))\n                if isinstance(hope_res, (dict, list)) and isinstance(real_res, (dict, list)):\n                    flag = handledict.cmp_dict(hope_res, real_res)\n>                   assert flag\nE                   AssertionError\n\ncommon\\checkresult.py:84: AssertionError"}, "description": "测试数据源配置", "steps": [{"name": "测试LADP数据源配置成功", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"E:\\Wondersoft_ApiTest\\common\\runcase.py\", line 59, in excute_case\n    self.excute_apicase(api, api_casedata)\n  File \"E:\\Wondersoft_ApiTest\\common\\runcase.py\", line 133, in excute_apicase\n    self.apicase_processors(api_casedata['postProcessors'], recv_data, recv_code)\n  File \"E:\\Wondersoft_ApiTest\\common\\runcase.py\", line 154, in apicase_processors\n    checkresult.check_result(pro_data['assert'], recv_data, recv_code)\n  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 31, in check_result\n    assert_response(value, real_res)\n  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 84, in assert_response\n    assert flag\n"}, "steps": [{"name": "发送请求", "status": "passed", "attachments": [{"name": "请求方法：", "source": "e871138f-537f-4c17-9c88-8a6aaf7b0206-attachment.attach"}, {"name": "请求地址", "source": "6c71a56f-5e43-48ae-99a1-0574d43554f7-attachment.attach"}, {"name": "请求头", "source": "13372b4c-c4ba-4f1e-ac9f-b5ead78d350d-attachment.attach"}, {"name": "请求参数", "source": "3992ca83-366f-4be2-810c-be2fb194d2a9-attachment.attach"}, {"name": "请求结果", "source": "eb77b962-e2e6-4b7a-a4ea-dd0fb5f4ed29-attachment.attach"}], "start": 1692256760091, "stop": 1692256761112}, {"name": "结果校验", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 31, in check_result\n    assert_response(value, real_res)\n  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 84, in assert_response\n    assert flag\n"}, "steps": [{"name": "状态码校验", "status": "passed", "attachments": [{"name": "期望状态码", "source": "51a0db48-0f49-4bd3-9511-d79163b875e9-attachment.attach"}, {"name": "实际状态码", "source": "92f5294d-bb21-4fe9-98e0-ef841533d3c4-attachment.attach"}], "start": 1692256761112, "stop": 1692256761113}, {"name": "返回值校验", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"E:\\Wondersoft_ApiTest\\common\\checkresult.py\", line 84, in assert_response\n    assert flag\n"}, "attachments": [{"name": "期望返回值", "source": "d4e69106-2215-4b4e-a783-415209cd4593-attachment.attach"}, {"name": "实际返回值", "source": "1bcc6eb4-d7e1-423d-a3aa-4188e8feb212-attachment.attach"}], "start": 1692256761113, "stop": 1692256761114}], "start": 1692256761112, "stop": 1692256761114}], "start": 1692256760089, "stop": 1692256761114}], "attachments": [{"name": "log", "source": "8fa4287c-ca59-4b64-8330-378e01e40482-attachment.txt", "type": "text/plain"}], "start": 1692256760085, "stop": 1692256761114, "uuid": "c65762d9-4a98-4498-b1f5-fa06236257d5", "historyId": "f25bd64294e77074dd8fcf15a47c34e2", "testCaseId": "2cc05bdd47264d0a6d036e2b95402968", "fullName": "testcases.test_cases.TestUserSync#test_businesscases", "labels": [{"name": "epic", "value": "用户管理"}, {"name": "feature", "value": "用户同步管理"}, {"name": "story", "value": "用户同步"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_cases"}, {"name": "subSuite", "value": "TestUserSync"}, {"name": "host", "value": "OFYI7JX9DURTDV6"}, {"name": "thread", "value": "18048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_cases"}]}